name: "Build & Release"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build with ufbt"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jammer_beta
          path: ${{ steps.build-app.outputs.fap-artifacts }}

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: "Publish to GitHub Releases"
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jammer_beta

      - name: Shorten SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ steps.vars.outputs.SHORT_SHA }}
          name: "Build ${{ steps.vars.outputs.SHORT_SHA }}"
          files: "*.fap"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
